name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata  # базовый контент (информация о пользователе) # 不知道是啥意思

          # 点赞地图
          plugin_stargazers: yes
          plugin_stargazers_charts: no
          plugin_stargazers_worldmap: yes
          plugin_stargazers_worldmap_token: ${{ secrets.GOOGLE_MAP_TOKEN }}
          plugin_stargazers_worldmap_sample: 200

          # random code snippet
          plugin_code: yes
          plugin_code_languages: javascript, typescript
          plugin_code_load: 400

          # contribution record
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # recently star repo
          plugin_stars: yes
          plugin_stars_limit: 5

          # sky line
          plugin_skyline: yes  # плагин 3д активности скайлайн
          plugin_skyline_year: 2024 # за какой год
          plugin_skyline_frames: 120  # количество кадров
          plugin_skyline_quality: 1  # качество 1 - лучшее

